# Generated by Django 4.0.5 on 2022-06-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_treadmodel_messagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='treadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='TreadModel',
        ),
    ]
