# Generated by Django 4.0.5 on 2022-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_treadmodel_receiver_remove_treadmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(to='core.post'),
        ),
    ]
