# Generated by Django 4.0.5 on 2022-06-18 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_commentmodel_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
